### ISSUE TITLE
Add documentation + more info

### ISSUE THREAD

**Issue by chez14** [butterfly-project/composer-info#1]
Hi, i like your project, do you mind to add more documentation and more info for [PackageInfo.php](https://github.com/butterfly-project/composer-info/blob/master/src/PackageInfo.php)??

Thank you!

**Comment by chez14** [comment]
Ping @AgreGAD :wink:

I'll make a PR if you still managing this project, but if you're not anymore, i'll maintain this project, what do you think?

**Comment by AgreGAD** [comment]
The class gives the minimum information on packages. It was required for me to organize the work of the packages

**Comment by AgreGAD** [comment]
I will be glad to your contribution

**Comment by chez14** [comment]
Good to hear! So i just need to make a PR, correct?

I needed more information of the packages, like the author, license and descriptions. I need those to lazily generate the credit page, so i don't have to deal with the package i used one by one.

**Comment by AgreGAD** [comment]
> Good to hear! So i just need to make a PR, correct?

Yes, is correct!

**Comment by chez14** [comment]
@AgreGAD Please review, thanks!

**Comment by chez14** [comment]
Ah sorry @AgreGAD, mind to add a release version for composer, so i can do `composer update` without moving the version to `dev-master`?
